services:
  getlogger:
    restart: always
    build:
      context: .
    ports:
      - '8080:8080'
    expose:
      - '8080'
    env_file:
      - .env
    volumes:
      - datastore:/datastore

volumes:
  datastore: